import ProfileScreen from "../containers/ProfileScreen";


export default Strings ={
    ar: {
        error:{
            tooShort:'كلمة السر ضعيفة',
            fillAll:'يجب ملأ كل المعلومات',
            sendingError:'يرجى اعادة المحاولة'
        },
        success:{
            sentSuccessfuly:'تمت العملية بنجاح',
        },
        classes:'الاقسام',
        noResults:'لا توجد اعلانات في هده الفئة :( ',
        errorInEmailForm:'خطأ في البريد الإلكتروني',
        errorMatchPassword:'كلمة المرور غير متطابقه',
        require:'مطلوب',
        errorSignupMessage:'خطأ اثناء تسجيل الحساب',
        prodvider: 'مقدم الخدمة',
        login: 'تسجيل الدخول',
        signup: 'حساب جديد',
        forgetPassword: 'نسيت كلمة المرور',
        email: 'البريد الالكتروني',
        password: 'كلمة المرور',
        verify_password:'اعد كلمة المرور ',
        address:'العنوان',
        price : 'السعر',
        errorLoginMessage: 'خطأ في الاسم او كلمة المرور الرجاء المحاوله مره اخرى',
        name: 'الإسم',
        mobile: 'رقم الهاتف',
        whatsapp:'رقم الواتساب',
        description:'وصف الاعلان',
        uploadImage:'حمل صورة',
        title:'عنوان الاعلان',
        chooseCategory:'اختر الفئة',
        chooseSubCategory:'اختر القسم',
        chooseCity:' اخترالمدينة',
        confirmPassword: 'تاكيد كلمة المرور',
        city:'المدينة',
        home:'الرئيسية',
        orders:'طلباتي',
        termsAndCondition:'الشروط والاحكام',
        aboutApp:'عن التطبيق',
        contactUs:'تواصل معنا',
        call : 'اتصال',
        report :'بلاغ',
        message :'الرسالة',
        subject :'الموضوع',
        logout:'خروج',
        send:'ارسال',
        partnershipRequest:`شكرا لاضافة اعلانك`,
        //ScreensTitle:
        partnership:'شحن الحساب',
        ProfileScreen:'الصفحة الشخصية',
        MainScreen:'الصفحة الرئيسية',
        HomeScreen:'الاعلانات',
        PolicyScreen:'شروط الخصوصية',
        myAds:'اعلاناتي',
        addAd :'اضف اعلان',
        page:'صفحة',
        why:'السبب...',
        now:'الحالية',
        previous:'السابقة',
        policy:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. In in feugiat dolor. Cras maximus lacus in tellus vulputate lobortis. Aenean sodales nulla sed sodales sagittis. Praesent ut neque magna. Mauris vel est nec ipsum fermentum ornare eget a nulla. Quisque molestie lectus purus. Cras gravida ligula eget felis convallis, et dapibus turpis faucibus. Praesent suscipit ultricies arcu, ut ultrices sapien dapibus ac. Sed neque diam, faucibus a erat eu, interdum suscipit mi. Proin rhoncus posuere ligula.
        Donec eget mi ante. Ut ac arcu scelerisque neque convallis feugiat sed dapibus lorem. Proin ut dui eu urna facilisis congue quis non neque. Aenean ligula nunc, semper sit amet quam in, dignissim blandit sem. Duis ac dui ligula. Donec sed justo commodo, accumsan quam condimentum, consequat nisl. Praesent vitae feugiat sem. Donec bibendum, nisi in venenatis posuere, eros dui eleifend est, eu tristique tellus orci sit amet ipsum. Donec rhoncus iaculis ex, vehicula ornare ipsum commodo sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin non arcu sed nulla dictum sollicitudin. Cras convallis condimentum massa ut tempor. Fusce volutpat odio mi, ac mollis enim mattis ut. Sed commodo convallis dictum. Phasellus fringilla venenatis ex, tristique laoreet metus rhoncus nec. Nunc quis tristique ex, a rhoncus augue.`,
        notAuth:'عذرا,, يجب عليك تسجيل الدخول أولا!',

    }
};
